version: "3"

services:
  postgres:
    image: ankane/pgvector:v0.4.4
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_volume:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres_volume:
